apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
  namespace: observability
  labels: { app: rolldice }
spec:
  replicas: 1
  selector:
    matchLabels: { app: rolldice }
  template:
    metadata:
      labels: { app: rolldice }
    spec:
      containers:
        - name: app
          image: ghcr.io/signoz/rolldice:latest
          ports: [{ containerPort: 8080 }]
          env:
            - name: HOST_IP
              valueFrom: { fieldRef: { fieldPath: status.hostIP } }
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "$(HOST_IP):4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=rolldice"
---
apiVersion: v1
kind: Service
metadata:
  name: rolldice
  namespace: observability
spec:
  selector: { app: rolldice }
  ports: [{ port: 80, targetPort: 8080 }]
