---
- name: Uninstall SigNoz k8s-infra
  hosts: cluster
  gather_facts: false
  vars_files:
    - group_vars/all.yaml
  tasks:
    - name: Uninstall helm release
      kubernetes.core.helm:
        name: "{{ release_name }}"
        release_namespace: "{{ namespace }}"
        state: absent
        wait: true
