---
- name: Install SigNoz k8s-infra
  hosts: cluster
  gather_facts: false
  vars_files:
    - group_vars/all.yaml
  tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: present

    - name: Add SigNoz helm repo
      kubernetes.core.helm_repository:
        name: "{{ helm_repo_name }}"
        repo_url: "{{ helm_repo_url }}"

    - name: Render overrides
      ansible.builtin.template:
        src: files/override-values.yaml.j2
        dest: /tmp/k8sinfra-overrides.yaml

    - name: Install/upgrade k8s-infra
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: "{{ chart_name }}"
        chart_version: "{{ chart_version | default(omit) }}"
        release_namespace: "{{ namespace }}"
        create_namespace: false
        values_files:
          - /tmp/k8sinfra-overrides.yaml
        wait: true
        update_repo_cache: true
